.TH SIOD 1C LOCAL 
.SH NAME
siod \- small scheme interpreter (Scheme In One Defun).
.SH SYNOPSIS
.B siod
[-hXXXXX] [-iXXXXX]
.SH DESCRIPTION
.I Siod
is a very small scheme interpreter which can be used for short calculations
or included as a command interpreter or extension/macro language in other
applications.

.RE
.SS COMMAND LINE OPTIONS
.TP 8
.BI \-h "XXXXX"
The
.I XXXXX
should be an integer, specifying the number of cons cells to
allocate in the heap. The default is 5000.
.TP
.BI \-i "XXXXX"
The 
.I XXXXX
should be the name of an init file to load before going into
the read/eval/print loop.
.SH FILES
siod.doc siod.scm
.PD
.SH SEE ALSO
.I Structure and Interpretation of Computer Programs
, by Ableson and Sussman, MIT PRESS.
.SH DIAGNOSTICS
Error messages may also set the variable errobj to the offending object.
.SH BUGS
Does not GC during EVAL, only before each READ/EVAL/PRINT cycle.
