$ CFLAGS = ""$ LFLAGS = ""
$!
$ CC'CFLAGS' SLIB.C
$ CC'CFLAGS' SLIBA.C
$ CC'CFLAGS' SIOD.C
$ LINK'LFLAGS' SIOD.OBJ,SLIB.OBJ,SLIBA.OBJ,SYS$INPUT:/OPT
SYS$LIBRARY:VAXCRTL/SHARE
$ SIOD == "$" + F$ENV("DEFAULT") + "SIOD"
